###########
# site.url, site.title

title: 'Tridentu Linux'
description: "The official website for Tridentu 2 Linux."
author: "Aerodos12"

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
url:  'https://tridentu.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

pages_excerpts: true
collections:
    changelogs:
        output: true

plugins:
  - jekyll-feed


exclude:
- README.md

paginate: 2

safe: true
lsi: false

