###########
# site.url, site.title

title: 'Tridentu Linux'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
url:  'https://tridentu.github.io'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

pages_excerpts: true
collections:
    - changelogs
        output: true

exclude:
- README.md


safe: true
lsi: false

